export const CHANGE_SELECTED_CATEGORY = 'CHANGE_SELECTED_CATEGORY';
export const CHANGE_SELECTED_FILTER = 'CHANGE_SELECTED_FILTER';

export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECIEVE_DATA';
export const ERROR = 'ERROR';